spring:
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      host:
      port:
    client:
      channels:
        api-clients:
          address: ""
        api-merchant-details:
          address: ""
  datasource:
    username: ""
    password: ""
    url: ""
    driver-class-name: ""
  jpa:
    hibernate:
      ddl-auto: update
  port:
cache:
  ttl:
    client-get-seconds: 3600
server:
  servlet:
    context-path: /api/v1