spring:
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  grpc:
    client:
      channels:
        api-clients:
          address: ""
        api-merchant-details:
          address: ""
        api-orders:
          address: ""
  data:
    redis:
      host:
      port:
      password:
  port:
cache:
  ttl:
    client-get-seconds: 3600
server:
  servlet:
    context-path: /api/v1